# Generated by Django 5.0.3 on 2024-03-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(null=True),
        ),
    ]
